import {FormEvent,useEffect,useState,type ReactNode} from 'react'
import {Navigate,Route,Routes,useNavigate} from 'react-router-dom'
import {useAuth} from './auth'
import {api,message} from './api'

type Meal={id:number;meal_type:'LUNCH'|'DINNER';meal_option_id:number|null;status:'SELECTED'|'CANCELLED'}
type Option={id:number;name:string;meal_type:'LUNCH'|'DINNER';available:boolean}
const Card=({title,children}:{title:string,children:ReactNode})=><section className="card"><h2>{title}</h2>{children}</section>
function Login(){const {login}=useAuth();const nav=useNavigate();const [error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await login(String(f.get('email')),String(f.get('password')));nav('/')}catch(e){setError(message(e))}};return <main className="login"><div className="brand"><span>AK</span><h1>Ayushman Kitchen</h1><p>Student meal subscriptions, simply managed.</p></div><form onSubmit={submit} className="card"><h2>Welcome back</h2><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={8} required/></label>{error&&<p className="error">{error}</p>}<button>Sign in</button></form></main>}
function MealAction({type,selection,plan,options,onDone}:{type:'LUNCH'|'DINNER';selection?:Meal;plan:string;options:Option[];onDone:()=>void}){const [option,setOption]=useState('');const [feedback,setFeedback]=useState('');const run=async(path:string)=>{try{await api({method:path==='/student/meals/change'?'put':'post',url:path,data:{meal_type:type,meal_option_id:option?Number(option):undefined}});setFeedback('Saved.');onDone()}catch(e){setFeedback(message(e))}};const choices=options.filter(o=>o.meal_type===type&&o.available);return <div className="meal"><div><strong>{type[0]+type.slice(1).toLowerCase()}</strong><small>{selection?.status==='CANCELLED'?'Cancelled':selection?'Confirmed':'Not selected'}</small></div>{plan==='PREMIUM'&&!selection&&<select value={option} onChange={e=>setOption(e.target.value)}><option value="">Choose option</option>{choices.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select>}<div className="actions">{!selection?<button onClick={()=>run('/student/meals/select')} disabled={plan==='PREMIUM'&&!option}>Confirm</button>:selection.status==='SELECTED'?<><button className="secondary" onClick={()=>run('/student/meals/cancel')}>Cancel</button>{plan==='PREMIUM'&&<><select value={option} onChange={e=>setOption(e.target.value)}><option value="">Change option</option>{choices.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select><button onClick={()=>run('/student/meals/change')} disabled={!option}>Change</button></>}</>:null}</div>{feedback&&<small className="feedback">{feedback}</small>}</div>}
function StudentDashboard(){const [data,setData]=useState<any>();const [error,setError]=useState('');const load=()=>api.get('/student/meals/today').then(r=>setData(r.data)).catch(e=>setError(message(e)));useEffect(()=>{void load()},[]);if(error)return <p className="error">{error}</p>;if(!data)return <p>Loading your meals…</p>;const meals:Meal[]=data.selections;const sub=data.subscription_status;return <><header><div><p className="eyebrow">TODAY’S MEALS</p><h1>Good day, {useAuth().user?.name?.split(' ')[0]}</h1></div></header>{sub!=='ACTIVE'?<p className="notice">Your {data.plan} subscription is {sub.toLowerCase()}. Contact the kitchen administrator to renew it.</p>:null}<div className="grid"><Card title="Subscription"><p className="plan">{data.plan}</p><p>Status: <b>{sub}</b></p></Card><Card title="Meal actions">{sub==='ACTIVE'?<><MealAction type="LUNCH" selection={meals.find(m=>m.meal_type==='LUNCH')} plan={data.plan} options={data.options} onDone={load}/><MealAction type="DINNER" selection={meals.find(m=>m.meal_type==='DINNER')} plan={data.plan} options={data.options} onDone={load}/></>:<p>Meal actions are unavailable until your subscription is renewed.</p>}</Card></div></>}
function AdminDashboard(){const [dash,setDash]=useState<any>();const [students,setStudents]=useState<any[]>([]);const [options,setOptions]=useState<Option[]>([]);const [error,setError]=useState('');const load=async()=>{try{const [a,b,c]=await Promise.all([api.get('/admin/dashboard'),api.get('/admin/students'),api.get('/admin/meal-options')]);setDash(a.data);setStudents(b.data);setOptions(c.data)}catch(e){setError(message(e))}};useEffect(()=>{load()},[]);const addOption=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/admin/meal-options',{name:f.get('name'),meal_type:f.get('meal_type'),available:true});e.currentTarget.reset();load()}catch(e){setError(message(e))}};const flip=async(o:Option)=>{await api.put('/admin/meal-options/'+o.id,{...o,available:!o.available});load()};return <>{error&&<p className="error">{error}</p>}<header><div><p className="eyebrow">ADMINISTRATION</p><h1>Kitchen overview</h1></div></header><div className="stats"><Card title="Students"><b>{dash?.students??'—'}</b></Card><Card title="Active subscriptions"><b>{dash?.active_subscriptions??'—'}</b></Card><Card title="Meals confirmed today"><b>{dash?.today_confirmed??'—'}</b></Card></div><div className="grid"><Card title="Premium meal options"><form className="inline" onSubmit={addOption}><input name="name" placeholder="Meal name" required/><select name="meal_type"><option>LUNCH</option><option>DINNER</option></select><button>Add</button></form><ul>{options.map(o=><li key={o.id}>{o.name} <em>{o.meal_type}</em><button className="link" onClick={()=>flip(o)}>{o.available?'Disable':'Enable'}</button></li>)}</ul></Card><Card title="Students"><div className="table"><div className="row head"><span>Name</span><span>ID</span><span>Plan</span><span>Expiry</span></div>{students.map(s=><div className="row" key={s.user.id}><span>{s.user.name}</span><span>{s.user.student_id}</span><span>{s.subscription?.plan||'—'}</span><span>{s.subscription?.expiry_date||'—'}</span></div>)}</div></Card></div></>}
function Layout({children}:{children:ReactNode}){const {user,logout}=useAuth();return <div className="shell"><nav><div className="logo">AK</div><b>Ayushman Kitchen</b><span className="spacer"/><span>{user?.name}</span><button className="link" onClick={()=>logout()}>Sign out</button></nav><main className="content">{children}</main></div>}
function Protected(){const {user,loading}=useAuth();if(loading)return <p className="center">Loading…</p>;if(!user)return <Navigate to="/login" replace/>;return <Layout>{user.role==='ADMIN'?<AdminDashboard/>:<StudentDashboard/>}</Layout>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/*" element={<Protected/>}/></Routes>}
